Admin/Controllers/BannersController.cs
using System.Web;
using System.Web.Mvc;
using Data.Entites;

namespace Admin.Controllers
{
    public class BannersController : Controller
    {
        // GET: Banners
        public ActionResult Index(int? page,string search = "")
        {
            ViewBag.Page = page;
            ViewBag.Search = search;
            return View(Application.BannerService.GetBanners(page,search));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Banner banner, HttpPostedFileBase Imagem)
        {
            if (ModelState.IsValid)
            {
                if (Application.BannerService.NewBanner(banner, Imagem)) return RedirectToAction("Index");
            }
            return View(banner);
        }

        public ActionResult Details(int id)
        {
            return View(Application.BannerService.GetBanner(id));
        }

        public ActionResult Edit(int id)
        {
            return View(Application.BannerService.GetBanner(id));
        }

        [HttpPost]
        public ActionResult Edit(Banner banner, HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                if (Application.BannerService.ChangeBanner(banner, img)) return RedirectToAction("Index");
            }
            return View(banner);
        }

        public ActionResult Delete(int id)
        {
            Application.BannerService.DeleteBanner(id);
            return RedirectToAction("Index");
        }
    }
}

Admin/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Admin/Controllers/PaisesController.cs
using System.Web;
using System.Web.Mvc;
using Data.Entites;

namespace Admin.Controllers
{
    public class PaisesController : Controller
    {
        // GET: Paises
        public ActionResult Index(int? page, string search = "")
        {
            ViewBag.Page = page;
            ViewBag.Search = search;
            return View(Application.PaisService.GetPaises(page,search));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Pais pais, HttpPostedFileBase Imagem)
        {
            if (ModelState.IsValid)
            {
                if (Application.PaisService.NewPais(pais, Imagem)) return RedirectToAction("Index");
            }

            return View(pais);
        }

        public ActionResult Details(int id)
        {
            return View(Application.PaisService.GetPais(id));
        }



    }
}

Admin/Views/Banners/Create.cshtml
@model Data.Entites.Banner
@{
    ViewBag.Title = "Adicionar banner";
}
<section class="content-header" style="border-bottom: 1px solid #f4f4f4;">
    <h1>Banners<small>Adicionar um novo banner</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Banners")">Banner</a></li>
        <li><a href="@Url.Action("Create","Banners")">Adicionar banner</a></li>
    </ol>
</section>
<section class="content">
    <div style="margin-top:50px;" class="content with-border">
        @using (Html.BeginForm("Create", "Banners", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()
            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Titulo)
                        @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Titulo)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Link)
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Link)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Texto)
                        @Html.TextBoxFor(model => model.Texto, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Texto)
                    </div>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8">
                                @Html.LabelFor(model => model.Imagem)
                                <input type="file" name="Imagem" id="Imagem" />
                                @Html.ValidationMessageFor(model => model.Imagem)
                            </div>
                            <div class="col-md-4">
                                <div class="callout callout-info">
                                    <h4>Tamanho ideal</h4>
                                    <p>1286px x 440px</p>
                                </div>
                            </div>
                        </div>
                        </div>
                    
                    <div class="form-group">
                        @Html.Label("Liberado?")
                        <input type="radio" name="Liberado" value="true" />Sim
                        <input type="radio" name="Liberado" value="false" />Não
                    </div>

                    <div class="box-footer">

                        <input type="submit" value="Salvar" class="btn btn-success" />

                        <a href="@Url.Action("Index")" class="btn btn-info">Voltar</a>


                    </div>
                </div>

            </div>
        }
    </div>
</section>

Admin/Views/Banners/Details.cshtml
@model Data.Entites.Banner
@{
    ViewBag.Title = "Detalhes do banner " + Model.Titulo;
}

<section class="content-header with-border">
    <h1>Banners<small>Detalhes de banner</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Banners")">Banner</a></li>
        <li><a href="@Url.Action("Details","Banners", new {id = Model.Id})">Detalhes de banner</a></li>
    </ol>
</section>



<section class="content">
    <div class="box">
        <div style="margin-top:50px" class="box-header with-border">

            <img src="~/conteudo/banners/@Model.Imagem" style="width:100%; height:400px;" />



        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered table-striped table-responsive" style="background-color:#CCCCCC;">
                <tbody>
                    <tr>
                <tbody>
                    <tr>
                        <td style=" width:200px;">
                            @Html.DisplayNameFor(model => model.Id)
                        </td>
                        <td>@Html.DisplayFor(model => model.Id)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Titulo)</td>

                        <td>@Html.DisplayFor(model => model.Titulo)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Texto)</td>

                        <td>
                            @if (string.IsNullOrEmpty(Model.Texto))
                            {
                                @:Nenhum
                        }
                            else
                            {
                                @Html.DisplayFor(modelItem => modelItem.Texto);
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Link)</td>
                        <td>
                            @if (string.IsNullOrEmpty(Model.Link))
                            {
                                @:Nenhum
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => modelItem.Link);
                            }
                        </td>
                    </tr>
                    
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.DataCadastro)</td>
                        <td>@Html.DisplayFor(model => model.DataCadastro)</td>
                        
                    </tr>
                </tbody>



            </table>

            <div class="box-footer">

                <a href="@Url.Action("Edit","Banners", new { id = Model.Id })" class="btn btn-warning">Editar</a>

                <a href="@Url.Action("Index", "Banners")" class="btn btn-info">Voltar</a>

            </div>

        </div>



    </div>

</section>

Admin/Views/Banners/Edit.cshtml
@model Data.Entites.Banner
@{
    ViewBag.Title = "Alterar banner";
}
<section class="content-header" style="border-bottom: 1px solid #f4f4f4;">
    <h1>Banners<small>Editar um banner</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Banners")">Banner</a></li>
        <li><a href="@Url.Action("Edit","Banners", new {id = Model.Id})">Alterar banner</a></li>
    </ol>
</section>

<section class="content">
    <div style="margin-top:50px;" class="content with-border">
        @using (Html.BeginForm("Edit", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()
            @Html.HiddenFor(model => model.Id)
       

            @Html.HiddenFor(model => model.Imagem)

            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Titulo)
                        @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Titulo)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Link)
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Link)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Texto)
                        @Html.TextBoxFor(model => model.Texto, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Texto)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Imagem)
                        <input type="file" name="img" id="img" />
                        <small>Atual:@Model.Imagem</small>
                        @Html.ValidationMessageFor(model => model.Imagem)

                    </div>
                    
                    <div class="form-group">
                        @Html.Label("Liberado?")
                        <input type="radio" name="Liberado" value="true" />Sim
                        <input type="radio" name="Liberado" value="false" />Não
                    </div>

                    <div class="box-footer">
                        <input type="submit" value="Salvar" class="btn btn-success" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Voltar</a>
                    </div>
                </div>

            </div>
        }
    </div>

</section>

Admin/Views/Banners/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Data.Entites.Banner>
@{
    ViewBag.Title = "Listagem de Banners";
}




<section class="content-header">
    <h1>Banners<small>Lista de banners cadastrados no sistema</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Banners")">Banner</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-primary" style="margin-top:30px">
        <div class="pull-right">
            <a style="margin:4px; color:white;" href="@Url.Action("Create")" class="btn btn-success bg-blue-gradient pull-right"><i class="fa fa-plus-circle white"></i>&nbsp;Adicionar Banner</a>
        </div>
        <div class="box-title">
            <h3 style="margin-left:10px">Busca</h3>
        </div>
        <div class="fc fc-ltr">

            @using (Html.BeginForm())
            {

                <table class="fc-header" style="width: 65%;">
                    <tbody>
                        <tr style="height: 48px;">
                            <td class="fc-header-left" style="width: 10px;"></td>
                            <td class="fc-header-center">
                                @Html.TextBox("Search", null, new { @class = "form-control", placeholder = "Busca" })
                            </td>
                            <td class="fc-header-right">
                                <input type="submit" value="Enviar" class="btn bg-blue-gradient margin" style="margin-left: 10px;" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            }
        </div>

    </div>

    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
            <thead>
                <tr role="row">
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 180px;">
                        @Html.DisplayNameFor(model => model.First().Id)
                    </th>
                    <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 223px;" aria-sort="descending">
                        @Html.DisplayNameFor(model => model.First().Titulo)
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 223px;">
                        @Html.DisplayNameFor(model => model.First().DataCadastro)
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 223px;">
                        @Html.DisplayNameFor(model => model.First().Liberado)
                    </th>
                    <th style="float:right">
                        Ações
                    </th>

                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {

                    foreach (var item in Model)
                    {
                        <tr role="row" class="odd">
                            <td class="sorting_1">@item.Id</td>
                            <td class="">@item.Titulo</td>
                            <td>@item.DataCadastro</td>
                            <td><span class="label label-@((!item.Liberado) ? "danger" : "success")">@((!item.Liberado) ? "Não" : "Sim")</span></td>
                            <td>
                                <div style="float:right;" class="btn-group">
                                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-warning btn-small"><i class="fa fa-edit"></i></a>

                                    <a href="@Url.Action("Details", new { id = item.Id })" class="btn bg-olive btn-small"><i class="fa fa-search-plus"></i></a>

                                    <a chave="@item.Id" href="#" class="btn btn-danger btn-small deletar"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td style="text-align: center;" class="sorting_1" colspan="4">Nenhum banner encontrado.</td>
                    </tr>
                }

            </tbody>

        </table>
        @if (Model.PageCount > 1)
        {
            <div class="box-footer clearfix no-border">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = ViewBag.Search }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
            </div>
        }
    </div>

</section>

@section scripts{

    <script>
        $(function () {
            //$("#example1").DataTable();
            $('#example1').DataTable({
                "paging": false,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": false,
                "autoWidth": false
            });
            $('#example1 th:last-child').removeClass('sorting');
        });

        $('.deletar').click(function(e) {
            e.preventDefault();
            alertify.confirm("Deseja apagar esse banner?", function () {
                var url = String("@Url.Action("Delete", new {id = 0})");
                url = url.replace("0", $(this).attr('chave'));
                location.href = url;
            },function () {
                      alertify.error('Cancelado.');
             });
        });
</script>
}

Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<section class="content-header">
    <h1>
        Home
        <small>CCAB - Administrativo</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
   
    </ol>
</section>

Admin/Views/Paises/Create.cshtml
@model Data.Entites.Pais
@{
    ViewBag.Title = "Adicionar país";
}
<section class="content-header" style="border-bottom: 1px solid #f4f4f4;">
    <h1>Países<small>Adicionar um novo país</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Paises")">Países</a></li>
        <li><a href="@Url.Action("Create", "Paises")">Adicionar país</a></li>
    </ol>
</section>
<section class="content">
    <div style="margin-top:50px;" class="content with-border">
        @using (Html.BeginForm("Create", "Paises", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()
            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nome)
                        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Nome)
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8">
                                @Html.LabelFor(model => model.Imagem)
                                <input type="file" name="Imagem" id="Imagem" />
                                @Html.ValidationMessageFor(model => model.Imagem)
                            </div>
                            <div class="col-md-4">
                                <div class="callout callout-info">
                                    <h4>Tamanho ideal</h4>
                                    <p>88px x 59px</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Liberado?")
                        <input type="radio" name="Liberado" value="true" />Sim
                        <input type="radio" name="Liberado" value="false" />Não
                    </div>

                    <div class="box-footer">

                        <input type="submit" value="Salvar" class="btn btn-success" />

                        <a href="@Url.Action("Index")" class="btn btn-info">Voltar</a>


                    </div>
                </div>

            </div>
        }
    </div>
</section>

Admin/Views/Paises/Details.cshtml
@model Data.Entites.Pais
@{
    ViewBag.Title = "Detalhes do país " + Model.Nome;
}

<section class="content-header with-border">
    <h1>Países<small>Detalhes de país</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Paises")">Países</a></li>
        <li><a href="@Url.Action("Details", "Paises", new { id = Model.Id })">Detalhes de país</a></li>
    </ol>
</section>



<section class="content">
    <div class="box">
     
        <div class="box-body">
            <table class="table table-bordered table-striped table-responsive" style="background-color:#CCCCCC;">
                <tbody>
                    <tr>
                <tbody>
                    <tr>
                        <td style=" width:200px;">
                            @Html.DisplayNameFor(model => model.Id)
                        </td>
                        <td>@Html.DisplayFor(model => model.Id)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Nome)</td>

                        <td>@Html.DisplayFor(model => model.Nome)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Imagem)</td>
                        <td><img src="~/conteudo/paises/@Model.Imagem" style="width:100%; height:400px;" /></td>
                    </tr>

                    <tr>
                        <td>@Html.DisplayNameFor(model => model.DataCadastro)</td>
                        <td>@Html.DisplayFor(model => model.DataCadastro)</td>

                    </tr>
                </tbody>



            </table>

            <div class="box-footer">

                <a href="@Url.Action("Edit","Banners", new { id = Model.Id })" class="btn btn-warning">Editar</a>

                <a href="@Url.Action("Index", "Banners")" class="btn btn-info">Voltar</a>

            </div>

        </div>



    </div>

</section>

Admin/Views/Paises/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Data.Entites.Pais>
@{
    ViewBag.Title = "Listagem de Banners";
}




<section class="content-header">
    <h1>Países<small>Lista de países cadastrados no sistema</small></h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Index","Paises")">Países</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-primary" style="margin-top:30px">
        <div class="pull-right">
            <a style="margin:4px; color:white;" href="@Url.Action("Create")" class="btn btn-success bg-blue-gradient pull-right"><i class="fa fa-plus-circle white"></i>&nbsp;Adicionar Banner</a>
        </div>
        <div class="box-title">
            <h3 style="margin-left:10px">Busca</h3>
        </div>
        <div class="fc fc-ltr">

            @using (Html.BeginForm())
            {

                <table class="fc-header" style="width: 65%;">
                    <tbody>
                        <tr style="height: 48px;">
                            <td class="fc-header-left" style="width: 10px;"></td>
                            <td class="fc-header-center">
                                @Html.TextBox("Search", null, new { @class = "form-control", placeholder = "Busca" })
                            </td>
                            <td class="fc-header-right">
                                <input type="submit" value="Enviar" class="btn bg-blue-gradient margin" style="margin-left: 10px;" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            }
        </div>

    </div>

    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
            <thead>
                <tr role="row">
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 180px;">
                        @Html.DisplayNameFor(model => model.First().Id)
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 223px;">
                        @Html.DisplayNameFor(model => model.First().DataCadastro)
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 223px;">
                        @Html.DisplayNameFor(model => model.First().Liberado)
                    </th>
                    <th style="float:right">
                        Ações
                    </th>

                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {

                    foreach (var item in Model)
                    {
                        <tr role="row" class="odd">
                            <td class="sorting_1">@item.Id</td>
                            <td>@item.DataCadastro</td>
                            <td><span class="label label-@((!item.Liberado) ? "danger" : "success")">@((!item.Liberado) ? "Não" : "Sim")</span></td>
                            <td>
                                <div style="float:right;" class="btn-group">
                                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-warning btn-small"><i class="fa fa-edit"></i></a>

                                    <a href="@Url.Action("Details", new { id = item.Id })" class="btn bg-olive btn-small"><i class="fa fa-search-plus"></i></a>

                                    <a chave="@item.Id" href="#" class="btn btn-danger btn-small deletar"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td style="text-align: center;" class="sorting_1" colspan="4">Nenhum país encontrado.</td>
                    </tr>
                }

            </tbody>

        </table>
        @if (Model.PageCount > 1)
        {
            <div class="box-footer clearfix no-border">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = ViewBag.Search }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
            </div>
        }
    </div>

</section>

@section scripts{

    <script>
        $(function () {
            //$("#example1").DataTable();
            $('#example1').DataTable({
                "paging": false,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": false,
                "autoWidth": false
            });
            $('#example1 th:last-child').removeClass('sorting');
        });

        $('.deletar').click(function(e) {
            e.preventDefault();
            alertify.confirm("Deseja apagar esse banner?", function () {
                var url = String("@Url.Action("Delete", new {id = 0})");
                url = url.replace("0", $(this).attr('chave'));
                location.href = url;
            },function () {
                      alertify.error('Cancelado.');
             });
        });
    </script>
}